services:
  api:
    image: license-manager
    environment:
      DEBUG: False
      ALLOWED_HOSTS: '*'
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./resources:/app/resources
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./database:/data/postgres
    ports:
      - "5432:5432"