[variables]
DEBUG = 'False'
ALLOWED_HOSTS = '*'

[start]
cmd = "python manage.py collectstatic --noinput && python manage.py migrate &&  uvicorn LicenseManager.asgi:application --host 0.0.0.0 --port 8000"